<template>
    <div>
        <div>
            <p>سیاست حفظ حریم خصوصی</p>
        </div>
        <div>
            <p>تاریخ آخرین نسخه: آبان 6، 1397</p>
        </div>
        <div>
            <p>معرفی</p>
            <p>.صدر کریپتو ("ما") متعهد به حفظ حریم شخصی افراد اطلاعاتی ما ("شما" یا "کاربر") است؛ در این سیاست ما توضیح می دهیم که چگونه اطلاعات شخصی شما، یعنی هر گونه اطلاعات مربوط به شما به عنوان شناسایی یا شناسایی طبیعی شخصی که ممکن است در مورد شما داشته باشد، جمع آوری، استفاده، ذخیره، افشا و حذف (هر و همه به عنوان "پردازش") است</p>
            <p>. ما اطلاعات شخصی قابل شناسایی را از کودکان زیر 16 سال جمع نمی کنیم. اگر فکر می کنید که یک کودک زیر سن 16 ساله ما را با اطلاعات شخصی شناسایی کرده است، لطفا با پشتیبانی مشتری تماس بگیرید</p>
            <p>. این سیاست فقط در مورد اطلاعاتی که ما پردازش می کند، اعمال می شود. این به شیوه های شرکت هایی که ما مالک یا کنترل نمی کنند و یا کارکنانی که مدیریت نمی کنند، اعمال نمی شود. اطلاعات در مورد خدمات ما ممکن است حاوی پیوندهایی به وب سایت های شخص ثالث باشد و هرگونه اطلاعاتی که به آن سایت ها ارائه می کنید، تحت پوشش هر گونه سیاست حفظ حریم خصوصی آنها قرار داشته باشد. لطفا مطمئن شوید که سیاست های حفظ حریم خصوصی هر سایت ثالثی را که بازدید می کنید، بخوانید. مسئولیت این سایت ها برای حفاظت از هر گونه اطلاعاتی است که به آنها داده اید، بنابراین ما نمی توانیم مسئولیت استفاده از اطلاعات شخصی شما را به عهده بگیریم</p>
            <p>. ما ممکن است این سیاست را به موقع به روز کنیم و به شما در مورد تغییرات این سیاست که به حقوق شما مربوط می شود را از طریق ایمیل و / یا با ارسال در وب سایت ما در صدر کریپتو اطلاع رسانی می کنیم</p>
        </div>
        <div>
            <p> اطلاعات شخصی شما و نحوه استفاده از آن</p>
            <p>در این بخش ما 2 قسمت قرار داده ایم</p>
            <p>.مقوله های کلی داده ها و انواع داده های شخصی که ممکن است ما پردازش کنیم</p>
            <p>منبع اطلاعات شخصی؛</p>
            <p>اهدافی که ما می توانیم داده های شخصی را پردازش کنیم؛ و</p>
            <p>.مبانی قانونی پردازش</p>
            <p>ممکن است داده های ثبت نام ("اطلاعات ثبت") پردازش شود. داده های ثبت نام ممکن است شامل نام کاربری و آدرس ایمیل شما باشد. منبع اطلاعات ثبت نام شما است. برای اینکه شما بتوانید از این سرویس استفاده کنید، اطلاعات ثبت نام لازم است. پایه های قانونی برای این پردازش، رضایت و عملکرد قرارداد بین شما و ما و / یا اقدامات خود را براساس درخواست شما برای وارد شدن به چنین قراردادی می گیرند؛</p>
            <p>ممکن است داده های حساب شما (داده های حساب کاربری) پردازش شود. داده های حساب ممکن است شامل نام کامل شما، آدرس ایمیل، نام کاربری، کشور و شماره تلفن باشد. منبع اطلاعات حساب شما است. داده های حساب ممکن است برای اهداف ارائه شده پردازش شوند خدمات ما، حصول اطمینان از امنیت کاربران و سرویس های ما و برقراری ارتباط با شما کاربران ممکن است نیاز به تنظیم نام کامل خود را به مشخصات کاربر خود را قبل از خرید بیتکوین آنلاین از برخی از معامله گران. نام کامل فقط به فروشندگان بتنی که با آنها باز شده معامله. تأیید نام کامل به محافظت از کاربران در برابر پرداخت های جعلی کمک می کند، اعتماد کاربر را افزایش می دهد و راه دیگری برای دسترسی به کیف پول صدر کریپتو کاربر در صورتی که رمز عبور از بین رفته یا حساب هک شده است فراهم می کند. شماره تلفن برای اهداف اطلاع رسانی استفاده می شود و یک جایگزین مکانیزم برای شناسایی کاربران در صورتی که رمز عبور از بین رفته یا حساب مورد هک شدن قرار گیرد. اساس قانونی برای این پردازش رضایت است؛ عملکرد قرارداد بین شما و ما و / یا اقدامات خود را بر اساس درخواست خود وارد کنید تا به چنین قراردادی وارد شوید و منافع قانونی ما، یعنی بهره برداری از مدل کسب و کار ما</p>
            <p>ممکن است اسناد هویت ما ("اطلاعات آی دی") را پردازش کنیم. تأیید حساب با شناسه در حال حاضر برای همه تبلیغ کنندگان و کاربران که حجم معاملات بیش از حد مشخص است، اجباری است. شناسه ممکن است شامل نام کامل شما، کشور، تاریخ تولد، شماره امنیت اجتماعی و جنسیت باشد. هدف از شناسایی داده ها، محافظت از کاربران ما از تقلب و کمک به ما برای جلوگیری، تشخیص و بررسی تقلب، پولشویی، فعالیت های جنایی یا سوء استفاده دیگر از سرویس ما است. علاوه بر این، با الزام دادن همه تبلیغ کنندگان به تأیید ID، ما برای ارائه یک تجربه تجاری قابل اعتماد، ایمن و مطمئن برای مشتریان ما، به ما کمک خواهد کرد. شناسه یک فرض قوی درباره مالکیت حساب ایجاد می کند و بنابراین تضمین می کند که ما می توانیم دسترسی به حساب شما را در صورت هک شدن حساب شما، بازگردانیم. اساس قانونی برای این پردازش رضایت و منافع قانونی ما و / یا توسط اشخاص ثالث یعنی جلوگیری، تشخیص و تحقیق در مورد تقلب، فعالیت های جنایی یا سوءاستفاده از سرویس ها و جلوگیری از مسائل امنیتی است</p>
            <p> ما ممکن است داده ها درباره استفاده شما از وب سایت و خدمات ما ("اطلاعات استفاده") پردازش کنیم. داده های استفاده عمدتا اطلاعات غیر شناسایی شخصی از نوعی است که مرورگرهای وب، سرورها و خدمات مانند گوگل، به طور معمول در دسترس هستند، مانند نوع مرورگر، اولویت زبان، سایت ارجاع، و زمان هر بازدید. سایر اطلاعات غیر شناسایی که ما ممکن است به آن دسترسی داشته باشیم شامل نحوه استفاده از سرویس (به عنوان مثال پرس و جوهای جستجو)، مکان تقریبی شما، کوکی ها توسط سایت ما و غیره است. داده های استفاده ممکن است شامل موارد زیر باشد: 1) ، اطلاعات کسب و کار و کمپین های ایمیل ("داده های تجزیه و تحلیل"). با استفاده از گوگل، اطلاعات ترافیک وب سایت جمع آوری می کنیم. داده های ردیابی رویداد را با کمک مخلوص کردن پانل جمع آوری می کنیم، و این اطلاعات همچنین ممکن است شامل آدرس ایمیل، آدرس آی دی و کد کشور شما باشد. 2) اطلاعاتی که ما عمدتا به دلایل فنی، امنیتی و / یا پیشگیری از تقلب یا خطاهای ردیابی ("داده های فنی") جمع آوری می کنیم. ما با کمک فرستادن اطلاعاتی را در مورد خطاهای وب سایت جمع آوری می کنیم که ممکن است گاهی اوقات حاوی اطلاعات استفاده باشد. ما همچنین وقایع خاصی را از اقدامات شما در سایت ما وارد می کنیم. مبنای قانونی برای این پردازش منافع قانونی ما و / یا اشخاص ثالث یعنی نظارت بر کیفیت خدمات و بهبود وب سایت و خدمات ما و همچنین جلوگیری، شناسایی و تحقیق در مورد تقلب، فعالیت جنایی یا سوءاستفاده دیگر خدمات است و برای جلوگیری از مسائل امنیتی</p>
            <p>ممکن است داده های مربوط به معاملات شما را که شما از طریق وب سایت ما ("اطلاعات تجاری") انجام می دهید، پردازش کنید. داده های تجاری ممکن است شامل شناسه تجارت، معاملات مبادله شده، روش پرداخت، اطلاعات تبلیغاتی، نام کاربری فروشنده، نام فروشنده، ارزش تجاری (در فیات)، ارزش تجاری (در بیت کوین)، قیمت بیت کوین، ارز، زمان های تجارت و چت تجاری به عنوان اطلاعات فاکتور تجاری ممکن است و داده های تجارت ATM. منبع اطلاعات تجاری شما و شریک تجاری شما است. اساس قانونی برای این پردازش، رضایت است. اجرای یک قرارداد بین شما و ما و / یا بر اساس درخواست شما اقدام به وارد شدن به چنین قراردادی و منافع قانونی خود، یعنی بهره برداری از مدل کسب و کار ما کنید</p>
            <p>.ممکن است داده های مربوط به معاملات بیت کوین را در کیف پول بیت کوین ("اطلاعات تراکنش بیت کوین") پردازش کنیم. اطلاعات ذخیره شده در معاملات دریافت شده ممکن است شامل برچسب زمانبر، مقدار بیت کوین، آدرس سپرده (منحصر به فرد) و شناسه تراکنش و سایر داده های قابل دسترس در دسترس از بلوک بیت کوین است. معاملات برداشت ممکن است شامل داده هایی مانند برچسب زمانی، مقدار بیت کوین، آدرس ارسالی، شناسه تراکنش و شرح باشد. منبع اطلاعات تجاری شما و / یا شریک تجاری شما است. اساس قانونی برای این پردازش، رضایت است. اجرای یک قرارداد بین شما و ما و / یا بر اساس درخواست شما اقدام به وارد شدن به چنین قراردادی و منافع قانونی خود، یعنی بهره برداری از مدل کسب و کار ما کنید</p>
            <p>.ما ممکن است اطلاعاتی را که در ارتباط با هر ارتباطی که برای ما ارسال می کنید یا آنچه که از طریق استفاده از خدمات ما ("اطلاعات ارتباطی") ایجاد می کنید، در نظر بگیرید. داده های ارتباطی عبارتند از: 1) تمام پیام ها، درخواست ها و سایر ارتباطات با پشتیبانی مشتری ما که ممکن است در طی روند بازنگری دعا و یا از طریق بلیط های پشتیبانی، ایمیل ها یا با استفاده از هر وسیله ارتباطی دیگر؛ و 2) پیوست های ارتباطی و فایل های شما که هنگام انجام معاملات با سایر کاربران ("پیام های چت تجاری") یا سایر داده هایی که شما عمدتا توسط ارتباط با دیگر کاربران ایجاد می کنید ایجاد می کنید. داده های ارتباطی ممکن است عبارتند از آدرس ایمیل، نام کاربری، آدرس آی پی، نام کامل، فایل های صوتی و تصویری و در صورت تأیید صحت شناسه دستی: عکس شناسه شخصی کاربر، عکس کاربر و عکس لایحه ی سودمند کاربر یا مرتبط اسناد داده های ارتباطی ممکن است برای برقراری ارتباط با شما، ثبت ضبط، برای بررسی و حل اختلافات، خدمات بهتر مشتریان ما و بهبود خدمات ما پردازش شود. پایه قانونی برای این پردازش منافع قانونی ما یعنی مدیریت مناسب وب سایت و کسب و کار ما است</p>
            <p>.ما ممکن است اطلاعاتی را که برای ما برای اعطای اطلاعیه های ایمیل، اعلان های اس ام اس و / یا خبرنامه ("اطلاعات اعلان") در اختیار ما قرار داده اید، پردازش کنید. داده های اعلان ممکن است شامل آدرس ایمیل شما، شماره تلفن، نام کاربری و نام کامل شما باشد. داده های اعلان ممکن است به منظور ارسال اطلاعیه های مربوطه و / یا خبرنامه شما پردازش شود. پایه قانونی برای این پردازش رضایت است. میتوانید با تماس با ما یا با کلیک روی پیوند لغو اشتراک در ایمیل، در هر نقطه، لغو اشتراک کنید</p>
            <p>.در ارتباط با فعالیت های شرح داده شده در بالا، ما می توانیم براساس تعاملات شما با محتوا که به خدمات ما ارائه می دهیم، و یا اطلاعاتی که از سرویس های خارجی بدست آورده اید (در بخش 4 توضیح داده شده است) انجام دهید. در موارد محدود، فرایندهای خودکار می توانند دسترسی به سرویس ما را محدود یا محدود نگه دارند اگر چنین فرایندهایی فعالیت هایی را تشخیص دهد که به نظر ما خطرناکی برای خدمات ما، کاربران یا اشخاص ثالث است. ما این اطلاعات را با توجه به منافع قانونی ما در حمایت از خدمات و برند ما پردازش می کنیم. جلوگیری، تشخیص و تحقیق درباره تقلب، فعالیت جنایی یا سوءاستفاده دیگر خدمات؛ بهینه سازی محصولات و خدمات ارائه شده و / یا مطابق با قوانین قابل اجرا</p>
            <p>.ما ممکن است هر گونه اطلاعات شخصی شما را برای ایجاد، تمرین یا دفاع از دعوی حقوقی، چه در دادرسی و چه در خارج از پرونده دادگاه، در صورت نیاز، پردازش کنیم. پایه قانونی برای این پردازش، منافع قانونی ما یعنی حمایت و تضمین حقوق قانونی ما، حقوق قانونی شما و حقوق قانونی دیگران است</p>
            <p>علاوه بر اهداف خاصی که می توانیم داده های شخصی شما را در این بخش 2 پردازش کنیم، می توانیم هر کدام از اطلاعات شخصی شما را نیز پردازش کنیم، در صورتی که چنین پردازشی برای رعایت یک تعهد قانونی که ما در آن قرار داریم یا به منظور برای محافظت از منافع حیاتی خود و یا منافع حیاتی دیگر شخص طبیعی</p>
            <p>.کلیه مقوله های عمومی فوق اطلاعات ممکن است حاوی اطلاعاتی باشد که به خودی خود شما را شناسایی نمی کند و بنابراین به عنوان اطلاعات شخصی محسوب نمی شود</p>
            <p>.لطفا سعی کنید از ارائه هر گونه اطلاعات شخصی غیر ضروری برای ما جلوگیری کنید</p>
            <p>.اطلاعاتی را انتخاب کنید تا به طور عمومی در خدمات ما نمایش داده شود</p>
            <p>.برخی از کاربران ممکن است تصمیم به ارسال اطلاعات شخصا یا اطلاعات حساس در مورد خودشان در استفاده عادی از خدمات ما داشته باشند. این می تواند از طریق استفاده از زمینه های پروفایل اختیاری، در تعاملات در انجمن های دولتی و استفاده از فروم ما در صدر کریپتو رخ دهد یا اگر یک تعامل خصوصی قبلی به صورت عمومی منتشر شود. اطلاعاتی مانند آن، که به صورت داوطلبانه در بخش های عمومی قابل مشاهده از خدمات ما قرار می گیرد، به عنوان عمومی شناخته می شود، حتی اگر در غیر این صورت به عنوان شخص شناسایی یا حساس در نظر گرفته شود. به همین ترتیب، این پروتکل ها در زیر ذکر نشده است؛ زیرا ما آن را کنترل نمی کنیم؛ شما انجام می دهید علاوه بر این، به طور داوطلبانه تبلیغ این اطلاعات به این معنی است که شما هرگونه حقوق حریم خصوصی را که ممکن است به طور معمول با توجه به آن اطلاعات داشته باشید از دست می دهید. این ممکن است شانس خود را برای دریافت ارتباطات ناخواسته مانند هرزنامه افزایش دهد</p>
            <p>.لطفا همچنین به یاد داشته باشید که اگر شما انتخاب کنید که اطلاعات شخصی قابل شناسایی را با استفاده از ویژگی های خاص خدمات ما در اختیار ما قرار دهید، افرادی که چنین اطلاعاتی را می خوانند ممکن است از افراد یا اشخاص دیگر بدون کنترل ما و بدون دانش خود استفاده کنند و موتورهای جستجو بتوانند این اطلاعات را فهرست نمایند. از این رو ما از شما بخواهیم به دقت در مورد محتویات هرگونه اطلاعات خاصی که ممکن است در خصوص محتوایی که ایجاد می کنید یا اطلاعاتی که از طریق سرویس های ما ارائه می دهید، به طور خصوصی فکر کنید</p>
            <p>ارائه اطلاعات شخصی شما به دیگران</p>
            <p>در این بخش ما4 قسمت تعیین کردیم</p>
            <p>خدمات خارجی ("پردازنده") که ما برای پردازش اطلاعات شخصی از طرف ما استفاده می کنیم؛</p>
            <p>انواع داده های شخصی که پردازنده ها پردازش می کنند.</p>
            <p>دلیل استفاده از آنها</p>
            <p>For processing ID data, we use netverify service by Jumio Corporation ("Jumio"), a company located in the United States. ID may contain your full name, country, date of birth, social security number and gender.</p>
            <p>4.3. For behaviour statistics, business intelligence and email campaigns we use the service by Mixpanel Inc ("Mixpanel"), a company located in the United States and for behaviour statistics and business intelligence also the service by Google LLC ("Google Analytics"), a company located in the United States. Data that we may provide to Mixpanel may include your email address, IP address and country code and that data is used by Mixpanel to generate information about your usage of our service. Data that we may provide to Google Analytics may include your IP address and that data is used by Google Analytics to generate information about your usage of our service. The reason for using them both is that their tracking methods differ considerably and we use them for those different purposes: Mixpanel is focused on event and behaviour tracking as well as for sending informational messages while Google Analytics is more focused on page views.</p>
            <p>4.4. For tracking server errors, we use the service by Functional Software Inc ("Sentry"), a company located in the United States. Error messages are rare but they may include your IP address. Sentry is used for monitoring and fixing errors and crashes.</p>
            <p>4.5. For processing notification data, we use the service by SendGrid Inc ("SendGrid"), a company located in the United States for delivering emails to users, and we may use the services by Nexmo Inc (located in the United States), Twilio Inc. (located in the United States) and TM4B Ltd. (located in the United Kingdom) for delivering SMS messages to users.</p>
            <p>4.6. LocalBitcoins.com forum is a third-party application embedded to our site. It is a service operated by Muut Inc ("Muut"), a company located in the United States. Personal data that users may on rare occasions generate by using forum is thus processed by Muut.</p>
            <p>4.7. In addition to the specific disclosures of personal data set out in this Section 4, we may also disclose your personal data 1) to our auditors, lawyers, accountants, consultants and other professional advisors insofar as it is reasonably necessary for the purposes of obtaining professional advice or managing legal disputes and risks; 2) where such disclosure is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests and/or the vital interests of a third-party.</p>
            <p>5. International Transfers of Your Personal Data</p>
            <p>5.1. We store your information primarily within the European Economic Area. However, some features and requirements of the service, involve transferring your information to third-party service providers outside the European Economic Area. We have described all those service providers above in the Section 4. Where such service providers are not established in a country ensuring an adequate level of protection within the meaning of Regulation (EU) 2016/679, such as the United States, the transfers will be covered by the standard data protection clauses adopted by the European Commission or by another appropriate safeguard mechanism such as the Privacy Shield Framework.</p>
            <p>6. Retaining and Deleting Personal Data</p>
            <p>6.1. This Section 6 sets out our data retention and deletion policies, which are designed to help ensure that we comply with our legal obligations in relation to the user’s right to be forgotten.</p>
            <p>6.2. Personal data that we process for any purpose or purposes shall not be kept for longer than is necessary for that purpose or those purposes.</p>
            <p>6.3. Users may request the deletion of their account through our site.</p>
            <p>6.4. We will retain and delete your personal data as follows:</p>
            <p>For all users who have deleted their account:</p>
            <p>Personally-identifiable analytics data is removed 14 days after account deletion.</p>
            <p>Notification data is not generally stored by our processors but they may retain activity logs for a short period of time (this time varies depending on the processor in question but is not greater than 13 months).</p>
            <p>For users who have not conducted or initiated any trades or bitcoin transactions to their wallet, we will delete all personal data 14 days after the approval of your account deletion request.</p>
            <p>For users who have conducted or initiated any trades or sent or received any bitcoin transactions using their wallet and whose account deletion request has been approved by us, our data deletion policy is the following:</p>
            <p>Your public profile and advertisements will be hidden 14 days after you delete your account.</p>
            <p>Your communication data will be deleted 5 years after you delete your account. Trade chat messages are deleted 180 days after the trade is completed. Trade chat messages from disputed trades will be deleted 5 years after you delete your account.</p>
            <p>Your registration data, account data, ID data, trade data and technical data will be deleted 5 years after you delete your account.</p>
            <p>Bitcoin transaction data from our internal systems will be removed 5 years after you delete your account, with the exception of publicly available information on the bitcoin blockchain.</p>
            <p>6.5. In some cases it is not possible for us to specify in advance the periods for which your personal data will be retained. In such cases, we will determine the period of retention based on the period we need to access the data for the provision of services, receiving payment, resolving your customer support issue or other issues or for any other auditing or legal reasons.</p>
            <p>6.6. Notwithstanding the other provisions of this Section 6, we may retain your personal data where such retention is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.</p>
            <p>7. Your Rights</p>
            <p>7.1. In this Section 7, we have summarised the principal rights that you have under data protection law. Some of the rights are complex, might contain restrictions depending on the legal basis for processing the data and not all of the details have been included in our summaries. Accordingly, you should read the relevant laws and guidance from the regulatory authorities for a full explanation of these rights.</p>
            <p>7.2. Your principal rights under data protection law are:</p>
            <p>(a) the right to access;</p>
            <p>You have the right to confirmation as to whether or not we process your personal data and, where we do, access to the personal data. Providing the rights and freedoms of others are not affected, we will supply to you a copy of your personal data. The first copy will be provided free of charge, but additional copies may be subject to a reasonable fee. You can ask for your personal data by contacting our customer support.</p>
            <p>(b) the right to rectification;</p>
            <p>You have the right to have any inaccurate personal data about you rectified and, taking into account the purposes of the processing, to have any incomplete personal data about you completed.</p>
            <p>(c) the right to erasure;</p>
            <p>You have the right to the erasure of your personal data. We have described our policy for retaining and deleting personal data above in Section 6.</p>
            <p>(d) the right to object to processing;</p>
            <p>You have the right to object to our processing of your personal data on grounds relating to your particular situation, but only to the extent that the legal basis for the processing is that the processing is necessary for: the performance of a task carried out in the public interest or in the exercise of any official authority vested in us; or the purposes of the legitimate interests pursued by us or by a third party. If you make such an objection, we will cease to process the personal information unless we can demonstrate compelling legitimate grounds for the processing which override your interests, rights and freedoms, or the processing is for the establishment, exercise or defence of legal claims.</p>
            <p>(e) the right to data portability;</p>
            <p>To the extent that the legal basis for our processing of your personal data is consent, and such processing is carried out by automated means, you have the right to receive your personal data from us in a structured, commonly used and machine-readable format. However, this right does not apply where it would adversely affect the rights and freedoms of others.</p>
            <p>(f) the right to complain to a supervisory authority;</p>
            <p>If you consider that our processing of your personal information infringes data protection laws, you have a legal right to lodge a complaint with a supervisory authority responsible for data protection. You may do so in the EU member state of your habitual residence, your place of work or the place of the alleged infringement.</p>
            <p>(g) the right to withdraw consent.</p>
            <p>(g) the right to withdraw consent.</p>
            <p>To the extent that the legal basis for our processing of your personal information is consent, you have the right to withdraw that consent at any time. Withdrawal will not affect the lawfulness of processing before the withdrawal.</p>
            <p>7.3. Without prejudice to the aforementioned, if we have reasonable doubts concerning the identity of a user exercising his/her rights referred to in Section 7.2 or if we otherwise due to security reasons deem it necessary, we may request the provision of additional information and otherwise use all reasonable measures necessary to confirm the identity of the user.</p>
            <p>7.4. You may exercise any of your rights in relation to your personal data by contacting our customer support. Concerning "Right to erasure" users are also able to request the deletion of their account through our site.</p>
            <p>8.Cookie Policy</p>
            <p>(a) What are cookies</p>
            <p>As is common practice with almost all professional websites, this site uses cookies, which are tiny files that are saved to your web browser, to improve your experience and to enable certain features, such as authentication. This page describes what information they gather, how we use it and why we sometimes need to store these cookies. We will also share how you can prevent these cookies from being stored, however this may downgrade or 'break' certain elements of the sites functionality.</p>
            <p>Cookies may be either "persistent" cookies or "session" cookies: a persistent cookie will be stored by a web browser and will remain valid until its set expiry date, unless deleted by the user before the expiry date; a session cookie, on the other hand, will expire at the end of the user session, when the web browser is closed.</p>
            <p>Cookies do not typically contain any information that personally identifies a user, but personal information that we store about you may be linked to the information stored in and obtained from cookies.</p>
            <p>For more general information on cookies see the Wikipedia article on HTTP Cookies.</p>
            <p>(b) Cookies that we use</p>
            <p>If you create an account with us then we will use cookies for the management of the signup process, for general administration and for preventing abuse and misuse of our services.</p>
            <p>We use cookies when you are logged in so that we can remember this fact. This prevents you from having to log in every single time you visit a new page. These cookies are typically removed or cleared when you log out to ensure that you can only access restricted features and areas when logged in.</p>
            <p>When you submit data through a form such as those found on contact pages or comment forms, cookies may be set to remember your user details for future correspondence. In order to provide you with a great experience on this site, we provide the functionality to set your preferences for how this site runs when you use it. In order to remember your preferences we need to set cookies so that this information can be called whenever you interact with a page that is affected by your preferences.</p>
            <p>We run an affiliate programme and as a part of it affiliates advertise our site and services. With the affiliate programme we use tracking cookies to track users who visit our site through one of our affiliate partner sites in order to credit them appropriately, and where applicable, allow our affiliate partners to provide you any bonus for making a purchase.</p>
            <p>(c) Cookies used by our service providers</p>
            <p>We use Google Analytics to analyse the use of our website. Google Analytics gathers information about website use by means of cookies. The information gathered relating to our website is used to create reports about the use of our website and how we might improve your experience. These cookies may track things such as how long you spend on the site and the pages that you visit. Google's privacy policy is available at: https://www.google.com/policies/privacy/.</p>
            <p>In addition, Cloudflare will add a security cookie to any domain or subdomain that is being proxied by our service.</p>
            <p>(d) Managing cookies</p>
            <p>You can prevent the setting of cookies by adjusting the settings on your browser (see your browser Help for how to do this). Disabling cookies will result in disabling all functionality and features of this site. Therefore it is recommended that you do not disable cookies.</p>
            <p>9. How to Contact Us</p>
            <p>9.1. The data controller responsible for your personal data for is LocalBitcoins Oy, a Finnish limited liability company; address Porkkalankatu 20, 00180 Helsinki, Finland. If you have any questions about this Privacy Policy, your rights and/or our data collection practices, please contact our customer support.</p>
            <p>Data Protection officers contact details</p>
            <p>sadrCrypto Oy / Data Protection Officer</p>
            <p>Porkkalankatu 20</p>
            <p>00180 Helsinki</p>
            <p>Finland</p>
            <p>dpo@sadrCrypto.com</p>
        </div>
    </div>
</template>
